services:
  youtube-status-core:
    build:
      context: .
      dockerfile: ./build-env/Dockerfile
    restart: always
    volumes:
      - type: bind
        source: ./
        target: /tmp/
        read_only: true
